### PR TITLE
Adding some more tests

### PR DESCRIPTION
**Pull request by goerch**
Two immediate issues:

- Some tests fail for dac_voronoi!
- Type restrictions impede testing floating point sites

### CODE REVIEW

**Comment by jacobusmmsmit** [comment]
A few comments:
- Floating point stuff should be in its own branch because I think it will require a bit of an overhaul to do properly.
- Dependencies used in testing are separate from those used in the package and have separate Project.toml files. As far as I know, we don't use `Distributions` in the source code so it shouldn't be a dependency in the DiscreteVoronoi Project.toml.
- The multiple tests caused by repetitions should be a single test that fails if *any* of a certain setup's tests failed. If any of the tests in a certain setup (algorithm, size, distance etc. combination) fail then we know what to look at to solve the bug, we don't need to know which test exactly failed.
- Put helper functions used in testing in its own file and include it, the current test file is getting pretty big. At one point we should split the tests into their own files and include them as well. Perhaps when we get to testing with Floats as well.

**Comment by goerch** [comment]
>     * Floating point stuff should be in its own branch because I think it will require a bit of an overhaul to do properly.

OK.

>     * Dependencies used in testing are separate from those used in the package and have separate Project.toml files. As far as I know, we don't use `Distributions` in the source code so it shouldn't be a dependency in the DiscreteVoronoi Project.toml.

Fixed.

>     * The multiple tests caused by repetitions should be a single test that fails if _any_ of a certain setup's tests failed. If any of the tests in a certain setup (algorithm, size, distance etc. combination) fail then we know what to look at to solve the bug, we don't need to know which test exactly failed.

The test sets are now nested to show which configuration is broken. I don't see a nice way to summarize the repetitions in one `@test`. Do you want me to collect the results of repetitions in a boolean vector and `@test` this vector then?

>     * Put helper functions used in testing in its own file and include it, the current test file is getting pretty big. At one point we should split the tests into their own files and include them as well. Perhaps when we get to testing with Floats as well.

Done.

**Comment by jacobusmmsmit** [comment]
> Do you want me to collect the results of repetitions in a boolean vector and @test this vector then?

I was thinking:
```{julia}
for setup in configurations
    test_passes = true
    for _ in repetitions
        test_passes || break
        test_passes = test_passes && voronoi_equality_function(setup)
    end
    @test test_passes
end
```

So it would break out as soon as a test failed and we'd know which setup caused it. No need to allocate a vector but no harm in it either.

**Comment by jacobusmmsmit** [comment]
For the benchmarks I think let's just put it in another repository entirely. It's useful to know but not really necessary for the package beyond specific testable things like number of allocations.

**Comment by jacobusmmsmit** [comment]
In the long term we should remove the `@test_broken` stuff but this LGTM :)

**Pull request merged**
